validate:
  stage: build
  image: node:18-alpine3.18
  before_script:
    - apk add --no-cache git make
  script:
    - npm ci || { echo "Install / package update failed." ; exit 1; }
    - |
      if [ ! -z "$( git status --porcelain )" ]; then
        echo "Install and build left changed files: package-lock checked in?"
        exit 1
      fi
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
